### ISSUE TITLE
Upgrade from alpha2 to alpha5 causes "unable to find policy `HashPolicy`"

### ISSUE THREAD

**Issue by arcreative** [venuu/jsonapi-authorization#77]
I have a feeling this is because I'm using my own authorizer, but it looks like https://github.com/venuu/jsonapi-authorization/commit/7ca89d50c5a17d77245312fd4bbc0b1d7e8ab1ff breaks your old suggestion to override changes to relationships as changes to the record itself:

`custom_pundit_authorizer.rb`
```rb
require 'pundit'

module JSONAPI
  module Authorization
    class CustomPunditAuthorizer < DefaultPunditAuthorizer

      def replace_fields(source_record, new_related_records)
        ::Pundit.authorize(user, source_record, 'update?')

        new_related_records.each do |record|
          ::Pundit.authorize(user, record, 'show?')
        end
      end

      def create_resource(source_class, related_records)
        ::Pundit.authorize(user, source_class, 'create?')

        related_records.each do |record|
          ::Pundit.authorize(user, record, 'show?')
        end
      end
    end
  end
end
```

That said, was there something in the works to relax these constraints with an initializer config option?

Full trace:
```sh
Internal Server Error: unable to find policy `HashPolicy` for `{:relation_type=>:to_one, :relation_name=>:bundle, :records=>#<Bundle id: "123", name: "Yadda yadda", created_at: "2017-07-03 17:53:13", updated_at: "2017-07-03 17:53:13">}` /Users/adam/.rvm/gems/ruby-2.3.1/gems/pundit-1.1.0/lib/pundit/policy_finder.rb:59:in `policy!'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/pundit-1.1.0/lib/pundit.rb:112:in `policy!'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/pundit-1.1.0/lib/pundit.rb:62:in `authorize'
/Users/adam/repos/arcreative/my-project/lib/jsonapi/authorization/custom_pundit_authorizer.rb:19:in `block in create_resource'
/Users/adam/repos/arcreative/my-project/lib/jsonapi/authorization/custom_pundit_authorizer.rb:18:in `each'
/Users/adam/repos/arcreative/my-project/lib/jsonapi/authorization/custom_pundit_authorizer.rb:18:in `create_resource'
/Users/adam/.rvm/gems/ruby-2.3.1/bundler/gems/jsonapi-authorization-d7dce7b61a18/lib/jsonapi/authorization/authorizing_processor.rb:115:in `authorize_create_resource'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:546:in `catch'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:546:in `block in default_terminator'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:170:in `block in halting'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:454:in `block in call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:454:in `each'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:454:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_create_resource_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/processor.rb:57:in `block in process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_operation_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/processor.rb:56:in `process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation.rb:16:in `process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:58:in `block in process_operation'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:63:in `with_default_handling'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:57:in `process_operation'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:29:in `block (2 levels) in process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:28:in `each'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:28:in `block in process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:43:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:93:in `block (2 levels) in transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.5/lib/active_record/transactions.rb:211:in `transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:92:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:42:in `transaction'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/operation_dispatcher.rb:24:in `process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:86:in `block in process_operations'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_process_operations_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:85:in `process_operations'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:77:in `process_request'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/jsonapi-resources-0.9.0/lib/jsonapi/acts_as_resource_controller.rb:29:in `create'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:188:in `process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:126:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:455:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal/rescue.rb:20:in `process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `instrument'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:126:in `process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionview-5.0.5/lib/action_view/rendering.rb:30:in `process'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal.rb:190:in `dispatch'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_controller/metal.rb:262:in `dispatch'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `each'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `serve'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:727:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.5/lib/active_record/migration.rb:553:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/rack/logger.rb:36:in `call_app'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `block in call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/static.rb:136:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/railties-5.0.5/lib/rails/engine.rb:522:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/Users/adam/.rvm/gems/ruby-2.3.1/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by arcreative** [comment]
I ended up copying the new block and changing `update?` to `show?` and it seems to work now, but just curious if there was a solution on the horizon :-)

**Comment by valscion** [comment]
Ah yes, thanks for the issue! This is indeed the exact reason why this exists in the 1.0 TODO list in https://github.com/venuu/jsonapi-authorization/issues/48

> [**PR / Help wanted**] The API of `DefaultPunditAuthorizer` methods could be changed to use keyword arguments
>   * Currently the API change is backwards-incompatible in a way that could be very confusing,
>     namely as `replace_to_one_relationship` has the same amount of parameters but are very
>     different than what there was before
>   * Keyword arguments are supported ever since Ruby 2.0 so we can use them

We did change the API quite drastically but as the arity of the method didn't change, you'll just get weird errors instead. As you said:

> I have a feeling this is because I'm using my own authorizer

...that sadly is exactly true.

The incoming second argument now looks like this:

https://github.com/venuu/jsonapi-authorization/blob/24bfed7949a35ecd668489f79a1b77516a5bd340/spec/jsonapi/authorization/default_pundit_authorizer_spec.rb#L289-L295

That is, it is:

* An array...
* ...with hashes as its items...
* ...and those items having three keys, `relation_name`, `relation_type` and `records`

We need this information in order to be able to authorize relationships in a more granular way. See the upcoming documentation PR for these here: https://github.com/venuu/jsonapi-authorization/pull/71

I'd love to have your comments in #71 and maybe hear whether the new solution we've got would remove your need of overriding the authorizer in the first place.

**Comment by arcreative** [comment]
@valscion I'll check it out, thanks!  I think my overriding issue with the authorization is that there's always some strange edge case that requires more information to behave properly.  This isn't specifically related to this relationship authorizer, but it does make me have to do hacky things like perform authorization logic in the resources since sometimes we don't have access to the context in certain situations.  

I'll read through all the relationships stuff and see if that helps--I realize that it's not really your responsibility to maintain everyones hacks, especially in alpha releases :-)

**Comment by valscion** [comment]
Yeah, we do try to allow all sorts of weird hacks, but supporting them is up to the hack creators themselves 😅
